Repository ronimizy/FluentSpreadsheets, pull requests merged in 2022-08, with the labels that each got.

#5 refactor: removed async visit methods
  .github/workflows/dotnet.yml
  Examples/FluentSpreadsheets.Examples.Students/FluentSpreadsheets.Examples.Students.csproj
  Examples/FluentSpreadsheets.Examples.Students/Program.cs
  README.md
  Source/FluentSpreadsheets.ClosedXML/Extensions/AlignmentExtensions.cs
  Source/FluentSpreadsheets.ClosedXML/Extensions/BorderExtensions.cs
  Source/FluentSpreadsheets.ClosedXML/Extensions/XlWorksheetExtensions.cs
  Source/FluentSpreadsheets.ClosedXML/FluentSpreadsheets.ClosedXML.csproj
  Source/FluentSpreadsheets.ClosedXML/Rendering/ClosedXmlComponentRenderer.cs
  Source/FluentSpreadsheets.ClosedXML/Rendering/ClosedXmlRenderCommand.cs
  Source/FluentSpreadsheets.ClosedXML/Visitors/ClosedXmlHandler.cs
  Source/FluentSpreadsheets.ClosedXML/Visitors/ClosedXmlVisitor.cs
  Source/FluentSpreadsheets.Playground/FluentSpreadsheets.Playground.csproj
  Source/FluentSpreadsheets.Playground/Program.cs
  Source/FluentSpreadsheets/ComponentImplementations/AdjustedComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/ColumnWidthComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/EmptyComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/HStackComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/LabelComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/RowHeightComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/ScaledComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/StylingComponents/Alignment/AlignmentComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/StylingComponents/Border/BorderStyleComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/StylingComponents/Border/LeadingBorderStyleComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/StylingComponents/Border/TopBorderStyleComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/StylingComponents/Border/TrailingBorderStyleComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/StylingComponents/StylingComponentBase.cs
  Source/FluentSpreadsheets/ComponentImplementations/VStackComponent.cs
  Source/FluentSpreadsheets/Components/ComponentBase.cs
  Source/FluentSpreadsheets/Components/IComponent.cs
  Source/FluentSpreadsheets/Extensions/ComponentAdjustmentExtensions.cs
  Source/FluentSpreadsheets/Extensions/ComponentAlignmentExtensions.cs
  Source/FluentSpreadsheets/Extensions/ComponentHeightWidthExtensions.cs
  Source/FluentSpreadsheets/Extensions/ComponentScaleExtensions.cs
  Source/FluentSpreadsheets/FluentSpreadsheets.csproj
  Source/FluentSpreadsheets/Models/Components/Axis.cs
  Source/FluentSpreadsheets/Models/Components/BorderType.cs
  Source/FluentSpreadsheets/Models/Components/HorizontalAlignment.cs
  Source/FluentSpreadsheets/Models/Components/Scale.cs
  Source/FluentSpreadsheets/Models/Components/Size.cs
  Source/FluentSpreadsheets/Models/Components/VerticalAlignment.cs
  Source/FluentSpreadsheets/Rendering/IComponentRenderer.cs
  Source/FluentSpreadsheets/Rendering/IRenderCommand.cs
  Source/FluentSpreadsheets/SheetBuilders/SheetBuilder.cs
  Source/FluentSpreadsheets/SheetSegments/ISheetSegment.cs
  Source/FluentSpreadsheets/Visitors/ComponentVisitor.cs
  Source/FluentSpreadsheets/Visitors/ComponentVisitorBase.cs
  Source/FluentSpreadsheets/Visitors/IComponentVisitor.cs
  Source/FluentSpreadsheets/Visitors/IComponentVisitorHandler.cs
Labels: refactoring

#6 Refactor: Change ClosedXmlHandler location
  Examples/FluentSpreadsheets.Examples.Students/Program.cs
  Source/FluentSpreadsheets.ClosedXML/Handlers/ClosedXmlHandler.cs
  Source/FluentSpreadsheets.ClosedXML/Rendering/ClosedXmlComponentRenderer.cs
Labels: area-closedxml

#4 Feat: Google sheets
  FluentSpreadsheets.sln
  README.md
  Source/FluentSpreadsheets.GoogleSheets/Extensions/AlignmentExtensions.cs
  Source/FluentSpreadsheets.GoogleSheets/Extensions/BorderExtensions.cs
  Source/FluentSpreadsheets.GoogleSheets/Extensions/IndexExtensions.cs
  Source/FluentSpreadsheets.GoogleSheets/Extensions/IndexRangeIndex.cs
  Source/FluentSpreadsheets.GoogleSheets/Factories/DimensionRangeFactory.cs
  Source/FluentSpreadsheets.GoogleSheets/Factories/SheetNameFactory.cs
  Source/FluentSpreadsheets.GoogleSheets/FluentSpreadsheets.GoogleSheets.csproj
  Source/FluentSpreadsheets.GoogleSheets/Handlers/GoogleSheetHandler.cs
  Source/FluentSpreadsheets.GoogleSheets/Models/Dimension.cs
  Source/FluentSpreadsheets.GoogleSheets/Models/MergeType.cs
  Source/FluentSpreadsheets.GoogleSheets/Models/ValueInputOption.cs
  Source/FluentSpreadsheets.GoogleSheets/Rendering/GoogleSheetComponentRenderer.cs
  Source/FluentSpreadsheets.GoogleSheets/Rendering/GoogleSheetRenderCommand.cs
  Source/FluentSpreadsheets.GoogleSheets/Tools/IsExternalInit.cs
  Source/FluentSpreadsheets.Playground/FluentSpreadsheets.Playground.csproj
  Source/FluentSpreadsheets.Playground/Program.cs
Labels: feature, area-google

#8 chore: exceptions
  Source/FluentSpreadsheets.GoogleSheets/Exceptions/GoogleSheetException.cs
  Source/FluentSpreadsheets.GoogleSheets/Exceptions/GoogleSheetsException.cs
  Source/FluentSpreadsheets.GoogleSheets/Factories/RenderCommandFactory.cs
  Source/FluentSpreadsheets.GoogleSheets/FluentSpreadsheets.GoogleSheets.csproj.DotSettings
  Source/FluentSpreadsheets/Exceptions/FluentSpreadsheetsException.cs
  Source/FluentSpreadsheets/Exceptions/InvalidStructureException.cs
  Source/FluentSpreadsheets/Exceptions/ValidationException.cs
  Source/FluentSpreadsheets/FluentSpreadsheets.csproj.DotSettings
  Source/FluentSpreadsheets/Models/Components/IndexRange.cs
  Source/FluentSpreadsheets/Models/Components/ScaleAmount.cs
  Source/FluentSpreadsheets/SheetBuilders/SheetBuilder.cs
Labels: area-core, chore

#9 chore: nuget
  README.md
  Source/FluentSpreadsheets.ClosedXML/FluentSpreadsheets.ClosedXML.csproj
  Source/FluentSpreadsheets.GoogleSheets/FluentSpreadsheets.GoogleSheets.csproj
  Source/FluentSpreadsheets/FluentSpreadsheets.csproj
Labels: chore

#10 Fix: IndexRange validation
  Source/FluentSpreadsheets/Models/Components/IndexRange.cs
Labels: bug, area-core

#11 Fix: dimension range
  Source/FluentSpreadsheets.GoogleSheets/Factories/DimensionRangeFactory.cs
Labels: bug, area-google

#12 chore: nuget
  Source/FluentSpreadsheets.ClosedXML/FluentSpreadsheets.ClosedXML.csproj
  Source/FluentSpreadsheets.GoogleSheets/FluentSpreadsheets.GoogleSheets.csproj
  Source/FluentSpreadsheets/FluentSpreadsheets.csproj
Labels: chore

#13 Refactor/sheet builder implementation
  Docs/Media/example-students.png
  Examples/FluentSpreadsheets.Examples.Students/Program.cs
  README.md
  Source/FluentSpreadsheets.Playground/Program.cs
  Source/FluentSpreadsheets/FluentSpreadsheets.csproj
  Source/FluentSpreadsheets/FluentSpreadsheets.csproj.DotSettings
  Source/FluentSpreadsheets/Models/Sheets/SheetSegmentModel.cs
  Source/FluentSpreadsheets/SheetBuilders/ISheetBuilder.cs
  Source/FluentSpreadsheets/SheetBuilders/SheetBuilder.cs
  Source/FluentSpreadsheets/SheetSegments/ISheetSegment.cs
  Source/FluentSpreadsheets/SheetSegments/PrototypeSheetSegmentBase.cs
  Source/FluentSpreadsheets/SheetSegments/SheetSegmentBase.cs
  Source/FluentSpreadsheets/Sheets/SegmentImplementations/HeaderRowSegmentBase.cs
  Source/FluentSpreadsheets/Sheets/SegmentImplementations/PrototypeHeaderRowSegmentBase.cs
  Source/FluentSpreadsheets/Sheets/SegmentImplementations/PrototypeSegmentBase.cs
  Source/FluentSpreadsheets/Sheets/SegmentImplementations/RowSegmentBase.cs
  Source/FluentSpreadsheets/Sheets/SegmentImplementations/SegmentBase.cs
  Source/FluentSpreadsheets/Sheets/Segments/IFooterSegment.cs
  Source/FluentSpreadsheets/Sheets/Segments/IHeaderRowFooterSegment.cs
  Source/FluentSpreadsheets/Sheets/Segments/IHeaderRowSegment.cs
  Source/FluentSpreadsheets/Sheets/Segments/IHeaderSegment.cs
  Source/FluentSpreadsheets/Sheets/Segments/IPrototypeHeaderSegment.cs
  Source/FluentSpreadsheets/Sheets/Segments/IPrototypeSegmentHeaderCustomizer.cs
  Source/FluentSpreadsheets/Sheets/Segments/IPrototypeSheetSegment.cs
  Source/FluentSpreadsheets/Sheets/Segments/IRowSegment.cs
  Source/FluentSpreadsheets/Sheets/Segments/ISheetSegment.cs
  Source/FluentSpreadsheets/Sheets/VisitorImplementations/FooterSegmentVisitor.cs
  Source/FluentSpreadsheets/Sheets/VisitorImplementations/HeaderSegmentVisitor.cs
  Source/FluentSpreadsheets/Sheets/VisitorImplementations/PrototypeFooterSegmentVisitor.cs
  Source/FluentSpreadsheets/Sheets/VisitorImplementations/PrototypeHeaderSegmentVisitor.cs
  Source/FluentSpreadsheets/Sheets/VisitorImplementations/PrototypeRowSegmentVisitor.cs
  Source/FluentSpreadsheets/Sheets/VisitorImplementations/RowSegmentVisitor.cs
  Source/FluentSpreadsheets/Sheets/VisitorImplementations/SheetSegmentVisitor.cs
  Source/FluentSpreadsheets/Sheets/Visitors/IFooterSegmentVisitor.cs
  Source/FluentSpreadsheets/Sheets/Visitors/IHeaderSegmentVisitor.cs
  Source/FluentSpreadsheets/Sheets/Visitors/IPrototypeHeaderSegmentVisitor.cs
  Source/FluentSpreadsheets/Sheets/Visitors/IRowSegmentVisitor.cs
  Source/FluentSpreadsheets/Sheets/Visitors/ISheetSegmentVisitor.cs
  Source/FluentSpreadsheets/Unit.cs
Labels: refactoring, area-core

#14 refactor: styling implementation
  Examples/FluentSpreadsheets.Examples.Students/Program.cs
  Source/FluentSpreadsheets.ClosedXML/Extensions/AlignmentExtensions.cs
  Source/FluentSpreadsheets.ClosedXML/Extensions/BorderExtensions.cs
  Source/FluentSpreadsheets.ClosedXML/Handlers/ClosedXmlHandler.cs
  Source/FluentSpreadsheets.GoogleSheets/Extensions/AlignmentExtensions.cs
  Source/FluentSpreadsheets.GoogleSheets/Extensions/BorderExtensions.cs
  Source/FluentSpreadsheets.GoogleSheets/Extensions/IndexRangeIndex.cs
  Source/FluentSpreadsheets.GoogleSheets/Factories/DimensionRangeFactory.cs
  Source/FluentSpreadsheets.GoogleSheets/Handlers/GoogleSheetHandler.cs
  Source/FluentSpreadsheets.GoogleSheets/Rendering/GoogleSheetComponentRenderer.cs
  Source/FluentSpreadsheets.Playground/Program.cs
  Source/FluentSpreadsheets/ComponentFactory.cs
  Source/FluentSpreadsheets/ComponentImplementations/StylingComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/StylingComponents/Alignment/AlignmentComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/StylingComponents/Border/BorderStyleComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/StylingComponents/Border/BottomBorderStyleComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/StylingComponents/Border/LeadingBorderStyleComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/StylingComponents/Border/TopBorderStyleComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/StylingComponents/Border/TrailingBorderStyleComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/StylingComponents/StylingComponentBase.cs
  Source/FluentSpreadsheets/Components/IStylingComponent.cs
  Source/FluentSpreadsheets/Extensions/ComponentAdjustmentExtensions.cs
  Source/FluentSpreadsheets/Extensions/ComponentAlignmentExtensions.cs
  Source/FluentSpreadsheets/Extensions/ComponentBorderExtensions.cs
  Source/FluentSpreadsheets/Extensions/ComponentExtensions.cs
  Source/FluentSpreadsheets/Extensions/ComponentHeightWidthExtensions.cs
  Source/FluentSpreadsheets/Extensions/ComponentScaleExtensions.cs
  Source/FluentSpreadsheets/Models/Components/Alignment.cs
  Source/FluentSpreadsheets/Models/Components/BorderStyle.cs
  Source/FluentSpreadsheets/Models/Components/FrameBorderStyle.cs
  Source/FluentSpreadsheets/Models/Components/HorizontalAlignment.cs
  Source/FluentSpreadsheets/Models/Components/Style.cs
  Source/FluentSpreadsheets/Models/Components/VerticalAlignment.cs
  Source/FluentSpreadsheets/Styles/Alignment.cs
  Source/FluentSpreadsheets/Styles/BorderStyle.cs
  Source/FluentSpreadsheets/Styles/BorderType.cs
  Source/FluentSpreadsheets/Styles/FrameBorderStyle.cs
  Source/FluentSpreadsheets/Styles/HorizontalAlignment.cs
  Source/FluentSpreadsheets/Styles/Style.cs
  Source/FluentSpreadsheets/Styles/VerticalAlignment.cs
  Source/FluentSpreadsheets/Visitors/ComponentVisitor.cs
  Source/FluentSpreadsheets/Visitors/IComponentVisitorHandler.cs
Labels: bug, refactoring, area-core

#15 chore: nuget
  Source/FluentSpreadsheets/FluentSpreadsheets.csproj
Labels: chore
