Repository ronimizy/FluentSpreadsheets, pull requests merged in 2022-09, with the labels that each got.

#18 fix: skipping nodes after node depletion
  .github/workflows/dotnet.yml
  FluentSpreadsheets.Test/FluentSpreadsheets.Test.csproj
  FluentSpreadsheets.Test/RowSheetTest.cs
  FluentSpreadsheets.sln
  Source/FluentSpreadsheets.ClosedXML/FluentSpreadsheets.ClosedXML.csproj
  Source/FluentSpreadsheets.GoogleSheets/FluentSpreadsheets.GoogleSheets.csproj
  Source/FluentSpreadsheets/FluentSpreadsheets.csproj
  Source/FluentSpreadsheets/TableScaling/Scaler.cs
  Source/FluentSpreadsheets/Tools/EnumeratorNode.cs
Labels: bug

#19 feat: cell aware label
  Source/FluentSpreadsheets.GoogleSheets/Extensions/IndexExtensions.cs
  Source/FluentSpreadsheets.GoogleSheets/FluentSpreadsheets.GoogleSheets.csproj
  Source/FluentSpreadsheets/ComponentFactory.cs
  Source/FluentSpreadsheets/ComponentImplementations/CellAwareComponent.cs
  Source/FluentSpreadsheets/Components/ICellAwareComponent.cs
  Source/FluentSpreadsheets/FluentSpreadsheets.csproj
  Source/FluentSpreadsheets/Visitors/ComponentVisitor.cs
  Source/FluentSpreadsheets/Visitors/IComponentVisitor.cs
Labels: feature

#20 Feat/cell background color
  Source/FluentSpreadsheets.ClosedXML/Extensions/XlRangeExtensions.cs
  Source/FluentSpreadsheets.ClosedXML/FluentSpreadsheets.ClosedXML.csproj
  Source/FluentSpreadsheets.ClosedXML/Handlers/ClosedXmlHandler.cs
  Source/FluentSpreadsheets.GoogleSheets/Extensions/ColorExtensions.cs
  Source/FluentSpreadsheets.GoogleSheets/FluentSpreadsheets.GoogleSheets.csproj
  Source/FluentSpreadsheets.GoogleSheets/Handlers/GoogleSheetHandler.cs
  Source/FluentSpreadsheets.Playground/Program.cs
  Source/FluentSpreadsheets/Extensions/ApplicableExtensions.cs
  Source/FluentSpreadsheets/Extensions/ComponentFillExtensions.cs
  Source/FluentSpreadsheets/FluentSpreadsheets.csproj
  Source/FluentSpreadsheets/Styles/Alignment.cs
  Source/FluentSpreadsheets/Styles/BorderStyle.cs
  Source/FluentSpreadsheets/Styles/FrameBorderStyle.cs
  Source/FluentSpreadsheets/Styles/IApplicable.cs
  Source/FluentSpreadsheets/Styles/Style.cs
Labels: feature, area-core

#21 Feat/frozen dimensions
  Source/FluentSpreadsheets.ClosedXML/FluentSpreadsheets.ClosedXML.csproj
  Source/FluentSpreadsheets.ClosedXML/Handlers/ClosedXmlHandler.cs
  Source/FluentSpreadsheets.GoogleSheets/FluentSpreadsheets.GoogleSheets.csproj
  Source/FluentSpreadsheets.GoogleSheets/Handlers/GoogleSheetHandler.cs
  Source/FluentSpreadsheets.Playground/Program.cs
  Source/FluentSpreadsheets/ComponentImplementations/AdjustedComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/ColumnWidthComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/FrozenComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/HStackComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/RowHeightComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/StylingComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/TopLevelComponentBase.cs
  Source/FluentSpreadsheets/ComponentImplementations/VStackComponent.cs
  Source/FluentSpreadsheets/Components/IFrozenColumnComponent.cs
  Source/FluentSpreadsheets/Components/IFrozenRowComponent.cs
  Source/FluentSpreadsheets/Extensions/FrozenComponentExtensions.cs
  Source/FluentSpreadsheets/FluentSpreadsheets.csproj
  Source/FluentSpreadsheets/Visitors/ComponentVisitor.cs
  Source/FluentSpreadsheets/Visitors/IComponentVisitor.cs
  Source/FluentSpreadsheets/Visitors/IComponentVisitorHandler.cs
Labels: feature, area-core

#22 fix: frozen dimension size evaluation
  FluentSpreadsheets.Test/RowSheetTest.cs
  Source/FluentSpreadsheets.ClosedXML/FluentSpreadsheets.ClosedXML.csproj
  Source/FluentSpreadsheets.GoogleSheets/FluentSpreadsheets.GoogleSheets.csproj
  Source/FluentSpreadsheets.Playground/Program.cs
  Source/FluentSpreadsheets/FluentSpreadsheets.csproj
  Source/FluentSpreadsheets/Visitors/ComponentVisitor.cs
Labels: bug

#23 Fix: Freeze in google sheets
  Source/FluentSpreadsheets.GoogleSheets/FluentSpreadsheets.GoogleSheets.csproj
  Source/FluentSpreadsheets.GoogleSheets/Handlers/GoogleSheetHandler.cs
Labels: bug, area-google

#26 Fix/structure pipeline
  Examples/FluentSpreadsheets.Examples.Students/Program.cs
  Examples/FluentSpreadsheets.Examples.Tables/Program.cs
  FluentSpreadsheets.Test/RowSheetTest.cs
  Source/FluentSpreadsheets.ClosedXML/FluentSpreadsheets.ClosedXML.csproj
  Source/FluentSpreadsheets.GoogleSheets/FluentSpreadsheets.GoogleSheets.csproj
  Source/FluentSpreadsheets.Playground/Program.cs
  Source/FluentSpreadsheets/ComponentFactory.cs
  Source/FluentSpreadsheets/ComponentGroupImplementations/ComponentGroupBase.cs
  Source/FluentSpreadsheets/ComponentGroupImplementations/CustomizerComponentGroup.cs
  Source/FluentSpreadsheets/ComponentGroupImplementations/ModifierComponentGroup.cs
  Source/FluentSpreadsheets/ComponentGroupImplementations/StylingComponentGroup.cs
  Source/FluentSpreadsheets/ComponentGroups/IComponentGroup.cs
  Source/FluentSpreadsheets/ComponentImplementations/AdjustedComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/CellAwareComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/ColumnWidthComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/ComponentBase.cs
  Source/FluentSpreadsheets/ComponentImplementations/EmptyComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/FrozenComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/LabelComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/RowHeightComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/ScaledComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/StylingComponent.cs
  Source/FluentSpreadsheets/ComponentImplementations/TopLevelComponentBase.cs
  Source/FluentSpreadsheets/Components/CustomComponent.cs
  Source/FluentSpreadsheets/Components/IBaseComponent.cs
  Source/FluentSpreadsheets/Components/IComponent.cs
  Source/FluentSpreadsheets/Components/IHStackComponent.cs
  Source/FluentSpreadsheets/Components/IStylingComponent.cs
  Source/FluentSpreadsheets/Components/IVStackComponent.cs
  Source/FluentSpreadsheets/ContainerImplementations/ContainerComponentBase.cs
  Source/FluentSpreadsheets/ContainerImplementations/HStackComponent.cs
  Source/FluentSpreadsheets/ContainerImplementations/HStackComponentBase.cs
  Source/FluentSpreadsheets/ContainerImplementations/ModifierHStackComponent.cs
  Source/FluentSpreadsheets/ContainerImplementations/ModifierVStackComponent.cs
  Source/FluentSpreadsheets/ContainerImplementations/StyledHStackComponent.cs
  Source/FluentSpreadsheets/ContainerImplementations/StyledVStackComponent.cs
  Source/FluentSpreadsheets/ContainerImplementations/VStackComponent.cs
  Source/FluentSpreadsheets/ContainerImplementations/VStackComponentBase.cs
  Source/FluentSpreadsheets/Containers/IComponentContainer.cs
  Source/FluentSpreadsheets/Containers/IHStackComponent.cs
  Source/FluentSpreadsheets/Containers/IVStackComponent.cs
  Source/FluentSpreadsheets/Extensions/BaseComponentExtensions.cs
  Source/FluentSpreadsheets/Extensions/ComponentExtensions.cs
  Source/FluentSpreadsheets/FluentSpreadsheets.csproj
  Source/FluentSpreadsheets/FluentSpreadsheets.csproj.DotSettings
  Source/FluentSpreadsheets/TableComponentImplementations/RowComponentBase.cs
  Source/FluentSpreadsheets/TableComponents/ICustomizerRowComponent.cs
  Source/FluentSpreadsheets/Tables/ITableCustomizer.cs
  Source/FluentSpreadsheets/Tables/RowTable.cs
  Source/FluentSpreadsheets/Visitors/ComponentVisitor.cs
Labels: bug

#27 refactor: readme
  README.md
Labels: documentation

#28 Fix/styles
  FluentSpreadsheets.Test/CascadeStyleTest.cs
  FluentSpreadsheets.Test/Models/HeaderData.cs
  FluentSpreadsheets.Test/Models/Lab.cs
  FluentSpreadsheets.Test/Models/LabPoints.cs
  FluentSpreadsheets.Test/Models/Student.cs
  FluentSpreadsheets.Test/Models/StudentPoints.cs
  FluentSpreadsheets.Test/Models/StudentPointsSheetData.cs
  FluentSpreadsheets.Test/RowSheetTest.cs
  FluentSpreadsheets.Test/Tables/StudentPointsRowTable.cs
  Source/FluentSpreadsheets.ClosedXML/FluentSpreadsheets.ClosedXML.csproj
  Source/FluentSpreadsheets.GoogleSheets/FluentSpreadsheets.GoogleSheets.csproj
  Source/FluentSpreadsheets/ComponentFactory.cs
  Source/FluentSpreadsheets/FluentSpreadsheets.csproj
  Source/FluentSpreadsheets/TableComponentImplementations/RowComponentBase.cs
  Source/FluentSpreadsheets/Tables/DynamicTable.cs
Labels: bug, area-core

#29 Fix/styles
  FluentSpreadsheets.Test/CascadeStyleTest.cs
  Source/FluentSpreadsheets.ClosedXML/FluentSpreadsheets.ClosedXML.csproj
  Source/FluentSpreadsheets.GoogleSheets/FluentSpreadsheets.GoogleSheets.csproj
  Source/FluentSpreadsheets/FluentSpreadsheets.csproj
  Source/FluentSpreadsheets/TableComponentImplementations/RowComponentBase.cs
  Source/FluentSpreadsheets/TableComponentImplementations/StylingRowComponent.cs
Labels: bug, area-core
